version: '3.8'

services:
  backend:
    image: ghcr.io/kimjunha1231/interview-prep-backend:latest
    container_name: interview-prep-backend
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - SPRING_PROFILES_ACTIVE=prod # 운영 프로파일 강제 지정
    restart: always
    networks:
      - interview-network

networks:
  interview-network:
    driver: bridge
